### ISSUE TITLE
Hi, This is Christoph from Upwork. 

### ISSUE THREAD

**Issue by SmartDellTalks** [Saverio3/nekoswap#1]
I just wanted to contact you here.
crazydev0206@gmail.com
This is my gmail. You can contact me here as well if you've got issue.
If you can share me your email or something for communication, that would be appreciated

**Comment by Saverio3** [comment]
Hey, here is my email as well [csav2203@gmail.com](url)
We will be in touch.

**Comment by SmartDellTalks** [comment]
Nice. I'll close this ticket for now then.
